package viewer;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Collection {
    public final String name;
    public final List<String> comicNames; // Store comic folder names in order
    public final List<String> comicIds; // Store comic UUIDs in order (prevents name collisions)
    public int rating;
    public final Set<String> tags;
    public String selectedThumbnailComic; // Which comic's thumbnail to use
    public boolean isAutoGenerated = false;  // true if created from folder structure
    public String folderPath = null;         // source folder path for auto-collections

    public Collection(String name) {
        this.name = name;
        this.comicNames = new ArrayList<>();
        this.comicIds = new ArrayList<>();
        this.rating = 0;
        this.tags = new HashSet<>();
        this.selectedThumbnailComic = null;
    }
}
