package viewer;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Represents a collection of comics with metadata.
 * This is the JSON-backed version of the Collection class.
 */
public class CollectionEntry {
    public String name;
    public List<String> comicIds = new ArrayList<>(); // UUIDs of comics in this collection (ordered)
    public int rating = 0;
    public Set<String> tags = new HashSet<>();
    public String selectedThumbnailComicId;
    public String seriesCoverPath = null; // User-selected custom cover image path (takes priority)
    public boolean isAutoGenerated = false;  // true if created from folder structure
    public String folderPath = null;         // source folder path for auto-collections
    public String lastReadComicId = null;    // ID of the last opened comic in this collection
    public boolean isManuallySorted = false; // true if user manually sorted the collection
    public Set<String> readComicIds = new HashSet<>(); // IDs of comics marked as fully read
    public boolean isCurrentlyReading = false; // true if user is currently reading this collection
    
    public CollectionEntry(String name) {
        this.name = name;
    }
    
    /**
     * Adds a comic to this collection by UUID.
     */
    public void addComic(String comicId) {
        if (!comicIds.contains(comicId)) {
            comicIds.add(comicId);
        }
    }
    
    /**
     * Removes a comic from this collection by UUID.
     */
    public void removeComic(String comicId) {
        comicIds.remove(comicId);
    }
    
    /**
     * Gets the number of comics in this collection.
     */
    public int getComicCount() {
        return comicIds.size();
    }
    
    /**
     * Gets the first comic ID in the collection (for default thumbnail).
     */
    public String getFirstComicId() {
        return comicIds.isEmpty() ? null : comicIds.get(0);
    }
    
    /**
     * Returns true if this auto-collection has user-defined metadata that should be persisted.
     */
    public boolean hasUserMetadata() {
        return rating > 0 || !tags.isEmpty() || selectedThumbnailComicId != null 
            || seriesCoverPath != null || lastReadComicId != null || isManuallySorted 
            || !readComicIds.isEmpty() || isCurrentlyReading;
    }
}
