package viewer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.*;
import java.util.List;

/**
 * Service class for managing collections and their UI interactions.
 * Handles collection parsing, serialization, dropdown menus, and context menus.
 */
public class CollectionService {
    
    private final ImageBrowserApp app;
    private final Map<String, Collection> collections;
    
    public CollectionService(ImageBrowserApp app, Map<String, Collection> collections) {
        this.app = app;
        this.collections = collections;
    }
    
    /**
     * Escapes comic names for storage in collections (handles backslashes and commas).
     */
    public String escapeComicName(String name) {
        return name.replace("\\", "\\\\").replace(",", "\\,");
    }
    
    /**
     * Unescapes comic names from storage format.
     */
    public String unescapeComicName(String escaped) {
        return escaped.replace("\\,", ",").replace("\\\\", "\\");
    }
    
    /**
     * Joins comic names using escape-aware formatting.
     */
    public String joinComicNames(List<String> comicNames) {
        StringBuilder result = new StringBuilder();
        boolean first = true;
        
        for (String name : comicNames) {
            if (!first) result.append(",");
            first = false;
            result.append(escapeComicName(name));
        }
        
        return result.toString();
    }
    
    /**
     * Splits comic names using escape-aware parsing.
     */
    public List<String> splitComicNames(String comicsString) {
        List<String> result = new ArrayList<>();
        StringBuilder current = new StringBuilder();
        boolean escape = false;
        
        for (int i = 0; i < comicsString.length(); i++) {
            char c = comicsString.charAt(i);
            
            if (escape) {
                current.append(c);
                escape = false;
            } else if (c == '\\') {
                escape = true;
            } else if (c == ',') {
                result.add(unescapeComicName(current.toString()));
                current.setLength(0);
            } else {
                current.append(c);
            }
        }
        
        // Add the last name
        if (current.length() > 0) {
            result.add(unescapeComicName(current.toString()));
        }
        
        return result;
    }
    
    /**
     * Loads collections - now handled by LibraryService JSON.
     * This method is kept for compatibility but does nothing.
     */
    public void loadCollections() {
        // Collections are now loaded by LibraryService from collections.json
        // Old Collection objects are synced from LibraryService in getCollections()
    }
    
    /**
     * Saves collections to storage via LibraryService (JSON).
     * No longer writes to collections.properties.
     */
    public void saveCollections() {
        // Sync to LibraryService JSON instead of properties
        LibraryService libraryService = app.getLibraryService();
        if (libraryService == null) return;
        
        for (Map.Entry<String, Collection> entry : collections.entrySet()) {
            String collectionName = entry.getKey();
            Collection oldCollection = entry.getValue();
            
            // Get or create CollectionEntry
            CollectionEntry collectionEntry = libraryService.getCollection(collectionName);
            if (collectionEntry == null) {
                collectionEntry = new CollectionEntry(collectionName);
            }
            
            // Sync fields from old Collection to CollectionEntry
            collectionEntry.rating = oldCollection.rating;
            collectionEntry.tags.clear();
            collectionEntry.tags.addAll(oldCollection.tags);
            collectionEntry.selectedThumbnailComicId = oldCollection.selectedThumbnailComic;
            collectionEntry.isAutoGenerated = oldCollection.isAutoGenerated;
            collectionEntry.folderPath = oldCollection.folderPath;
            
            // Sync comic IDs - use UUIDs directly if available, otherwise fall back to name lookup
            collectionEntry.comicIds.clear();
            
            // If the old Collection has comicIds stored, use them directly
            if (oldCollection.comicIds != null && !oldCollection.comicIds.isEmpty()) {
                collectionEntry.comicIds.addAll(oldCollection.comicIds);
            } else {
                // Fallback to name-to-ID conversion for backward compatibility
                for (String comicName : oldCollection.comicNames) {
                    String comicId;
                    // Use path-based lookup if collection has a folderPath (auto-generated collections)
                    if (oldCollection.folderPath != null && !oldCollection.folderPath.isEmpty()) {
                        comicId = findComicIdByNameAndPath(comicName, oldCollection.folderPath, libraryService);
                    } else {
                        // Fallback to name-only lookup for manual collections
                        comicId = findComicIdByName(comicName, libraryService);
                    }
                    if (comicId != null) {
                        collectionEntry.comicIds.add(comicId);
                    }
                }
            }
            
            // Save via LibraryService (writes to collections.json)
            libraryService.saveCollection(collectionEntry);
        }
    }
    
    /**
     * Finds a comic ID by its folder name using LibraryService.
     * Uses folderPath to prevent collisions when comics have the same name in different series.
     */
    private String findComicIdByName(String folderName, LibraryService libraryService) {
        for (ComicEntry entry : libraryService.getLibraryCache().values()) {
            if (entry.name.equals(folderName)) {
                return entry.id;
            }
        }
        return null;
    }

    /**
     * Finds a comic ID by its folder name and parent path using LibraryService.
     * This prevents collisions when comics have the same name in different series.
     */
    private String findComicIdByNameAndPath(String folderName, String parentPath, LibraryService libraryService) {
        for (ComicEntry entry : libraryService.getLibraryCache().values()) {
            if (entry.name.equals(folderName)) {
                // If parentPath is provided, check if the comic is within that path
                if (parentPath != null && !parentPath.isEmpty()) {
                    File comicFile = new File(entry.folderPath);
                    File parentFile = new File(parentPath);
                    // Check if comic's parent matches the provided parent path
                    if (comicFile.getParentFile() != null && 
                        comicFile.getParentFile().getAbsolutePath().equals(parentFile.getAbsolutePath())) {
                        return entry.id;
                    }
                } else {
                    return entry.id;
                }
            }
        }
        return null;
    }
    
    /**
     * Shows scrollable dropdown menu for collection with keyboard navigation.
     * Uses a non-modal JDialog with JScrollPane for better handling of large collections.
     */
    public void showCollectionDropdown(Collection collection, JPopupMenu[] activeDropdownRef) {
        System.out.println("DEBUG: Opening Collection Dialog for " + collection.name);
        
        LibraryService libraryService = app.getLibraryService();
        CollectionEntry collectionEntry = libraryService.getCollection(collection.name);
        String lastReadComicId = (collectionEntry != null) ? collectionEntry.lastReadComicId : null;
        
        // Create non-modal dialog
        JDialog dialog = new JDialog(app, false);
        dialog.setUndecorated(true);
        dialog.setLocationRelativeTo(app);
        
        final String[] lastReadIdRef = { lastReadComicId };
        
        // Main panel with dark theme and cyan border
        JPanel mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBackground(ApplicationService.getBackgroundMedium());
        mainPanel.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 2));
        
        // Header panel
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(ApplicationService.getBackgroundMedium());
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Title
        String icon = collection.isAutoGenerated ? "[Series]" : "[Coll]";
        JLabel titleLabel = new JLabel(icon + " " + collection.name, SwingConstants.CENTER);
        titleLabel.setForeground(ApplicationService.getAccentColor());
        titleLabel.setFont(new Font("Arial", Font.BOLD, 14));
        headerPanel.add(titleLabel, BorderLayout.NORTH);
        
        // Info panel
        String info = collection.rating + "/100";
        if (!collection.tags.isEmpty()) {
            info += " | Tags: " + String.join(", ", collection.tags);
        }
        JLabel infoLabel = new JLabel(info, SwingConstants.CENTER);
        infoLabel.setForeground(ApplicationService.getTextPrimary());
        infoLabel.setFont(new Font("Arial", Font.ITALIC, 10));
        headerPanel.add(infoLabel, BorderLayout.CENTER);
        
        // Button panel for Mark All / Clear All
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 5));
        buttonPanel.setBackground(ApplicationService.getBackgroundMedium());
        
        JButton markAllBtn = new JButton("Mark All Read");
        markAllBtn.setForeground(ApplicationService.getTextPrimary());
        markAllBtn.setBackground(ApplicationService.getInputBackground());
        markAllBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 1));
        markAllBtn.setFont(new Font("Arial", Font.PLAIN, 11));
        markAllBtn.addActionListener(e -> {
            libraryService.markAllAsRead(collection.name);
            refreshComicList(mainPanel, collection, libraryService, collectionEntry, lastReadComicId, dialog);
        });
        
        JButton clearAllBtn = new JButton("Clear Progress");
        clearAllBtn.setForeground(ApplicationService.getTextPrimary());
        clearAllBtn.setBackground(ApplicationService.getInputBackground());
        clearAllBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 1));
        clearAllBtn.setFont(new Font("Arial", Font.PLAIN, 11));
        clearAllBtn.addActionListener(e -> {
            libraryService.clearAllProgress(collection.name);
            lastReadIdRef[0] = null;
            refreshComicList(mainPanel, collection, libraryService, collectionEntry, null, dialog);
        });
        
        buttonPanel.add(markAllBtn);
        buttonPanel.add(clearAllBtn);
        headerPanel.add(buttonPanel, BorderLayout.SOUTH);
        
        mainPanel.add(headerPanel, BorderLayout.NORTH);
        
        // Read Collection button
        boolean hasProgress = lastReadComicId != null && !lastReadComicId.isEmpty();
        String buttonText = hasProgress ? "> Resume Reading" : "> Read Collection";
        JButton readCollectionBtn = new JButton(buttonText);
        readCollectionBtn.setForeground(ApplicationService.getAccentColor());
        readCollectionBtn.setBackground(ApplicationService.getInputBackground());
        readCollectionBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 1));
        readCollectionBtn.setFont(new Font("Arial", Font.BOLD, 12));
        readCollectionBtn.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        readCollectionBtn.addActionListener(e -> {
            dialog.dispose();
            // Build ordered list of folders from collection using comic IDs (not names)
            List<File> orderedFolders = new ArrayList<>();
            for (String comicId : collectionEntry.comicIds) {
                ComicEntry comicEntry = libraryService.getLibraryCache().get(comicId);
                if (comicEntry != null && comicEntry.folderPath != null) {
                    File folder = new File(comicEntry.folderPath);
                    if (folder.exists()) {
                        orderedFolders.add(folder);
                    }
                }
            }
            
            if (orderedFolders.isEmpty()) {
                JOptionPane.showMessageDialog(app,
                    "No comics from this collection were found in your library.",
                    "Collection Empty", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Smart Resume: If lastReadComicId exists, find and open that comic
            File comicToOpen = null;
            if (hasProgress && lastReadIdRef[0] != null) {
                ComicEntry lastReadEntry = libraryService.getLibraryCache().get(lastReadIdRef[0]);
                if (lastReadEntry != null && lastReadEntry.folderPath != null) {
                    File lastReadFolder = new File(lastReadEntry.folderPath);
                    if (lastReadFolder.exists()) {
                        comicToOpen = lastReadFolder;
                    }
                }
            }
            
            // If no progress found or comic not found, start from first
            if (comicToOpen == null) {
                comicToOpen = orderedFolders.get(0);
            }
            
            // IMMEDIATELY update lastReadComicId when opening via Read Collection button
            String openComicId = libraryService.getComicId(comicToOpen);
            if (openComicId != null) {
                libraryService.updateLastReadComic(collection.name, openComicId);
                System.out.println("DEBUG ReadCollection: Updated lastRead to " + openComicId);
            }
            
            app.openCollectionViewer(comicToOpen, orderedFolders, collection.name);
        });
        
        // Comic list panel inside scroll pane
        JPanel comicListPanel = new JPanel();
        comicListPanel.setLayout(new BoxLayout(comicListPanel, BoxLayout.Y_AXIS));
        comicListPanel.setBackground(ApplicationService.getBackgroundMedium());
        
        // Create comic rows
        List<JPanel> comicRows = new ArrayList<>();
        for (int i = 0; i < collection.comicNames.size(); i++) {
            String comicName = collection.comicNames.get(i);
            JPanel row = createComicRow(comicName, i, collection, collectionEntry, libraryService, 
                                        lastReadComicId, dialog, comicRows);
            comicRows.add(row);
            comicListPanel.add(row);
        }
        
        if (collection.comicNames.isEmpty()) {
            JLabel emptyLabel = new JLabel("No comics in collection", SwingConstants.CENTER);
            emptyLabel.setForeground(ApplicationService.getTextSecondary());
            emptyLabel.setFont(new Font("Arial", Font.ITALIC, 12));
            comicListPanel.add(emptyLabel);
        }
        
        // Scroll pane
        JScrollPane scrollPane = new JScrollPane(comicListPanel);
        scrollPane.setPreferredSize(new Dimension(350, 250));
        scrollPane.setMaximumSize(new Dimension(350, 400));
        scrollPane.setBorder(null);
        scrollPane.setBackground(ApplicationService.getBackgroundMedium());
        scrollPane.getViewport().setBackground(ApplicationService.getBackgroundMedium());
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        // Center panel with Read Collection button and scroll pane
        JPanel centerPanel = new JPanel(new BorderLayout());
        centerPanel.setBackground(ApplicationService.getBackgroundMedium());
        centerPanel.add(readCollectionBtn, BorderLayout.NORTH);
        centerPanel.add(scrollPane, BorderLayout.CENTER);
        centerPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        
        mainPanel.add(centerPanel, BorderLayout.CENTER);
        
        // Footer with Edit button
        JButton editBtn = new JButton("Edit Collection");
        editBtn.setForeground(ApplicationService.getTextPrimary());
        editBtn.setBackground(ApplicationService.getInputBackground());
        editBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 1));
        editBtn.setFont(new Font("Arial", Font.PLAIN, 11));
        editBtn.addActionListener(e -> {
            dialog.dispose();
            DialogService.showEditCollectionDialog(app, collection);
        });
        
        JPanel footerPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        footerPanel.setBackground(ApplicationService.getBackgroundMedium());
        footerPanel.setBorder(BorderFactory.createEmptyBorder(5, 0, 10, 0));
        footerPanel.add(editBtn);
        
        mainPanel.add(footerPanel, BorderLayout.SOUTH);
        
        dialog.add(mainPanel);
        
        // Pack dialog to fit content, then constrain max height
        dialog.pack();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int maxHeight = Math.min(400, screenSize.height - 100);
        if (dialog.getHeight() > maxHeight) {
            dialog.setSize(350, maxHeight);
        }
        dialog.setLocationRelativeTo(app);
        
        // Auto-close when dialog loses focus (user clicks away)
        dialog.addWindowFocusListener(new WindowAdapter() {
            @Override
            public void windowLostFocus(WindowEvent e) {
                if (dialog.isVisible()) {
                    dialog.dispose();
                }
            }
        });
        
        // Keyboard navigation
        dialog.addKeyListener(new KeyAdapter() {
            private int selectedIndex = -1;
            private boolean buttonHighlighted = false;
            
            @Override
            public void keyPressed(KeyEvent e) {
                int keyCode = e.getKeyCode();
                
                if (keyCode == KeyEvent.VK_ESCAPE) {
                    dialog.dispose();
                } else if (keyCode == KeyEvent.VK_LEFT || keyCode == KeyEvent.VK_RIGHT) {
                    // Highlight the Read Collection button
                    buttonHighlighted = true;
                    readCollectionBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 2));
                    readCollectionBtn.setBackground(ApplicationService.getBackgroundLight());
                    // Clear row selection
                    for (JPanel row : comicRows) {
                        row.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
                    }
                    selectedIndex = -1;
                } else if (keyCode == KeyEvent.VK_DOWN) {
                    if (buttonHighlighted) {
                        // Clear button highlight and move to first row
                        buttonHighlighted = false;
                        readCollectionBtn.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 1));
                        readCollectionBtn.setBackground(ApplicationService.getInputBackground());
                        if (comicRows.size() > 0) {
                            selectedIndex = 0;
                            updateSelection(comicRows, selectedIndex, scrollPane);
                        }
                    } else if (selectedIndex < comicRows.size() - 1) {
                        // Navigate down through rows
                        selectedIndex++;
                        updateSelection(comicRows, selectedIndex, scrollPane);
                    }
                } else if (keyCode == KeyEvent.VK_UP) {
                    if (selectedIndex > 0) {
                        selectedIndex--;
                        updateSelection(comicRows, selectedIndex, scrollPane);
                    }
                } else if (keyCode == KeyEvent.VK_ENTER) {
                    if (buttonHighlighted) {
                        // Trigger Read Collection button
                        readCollectionBtn.doClick();
                    } else if (selectedIndex >= 0 && selectedIndex < comicRows.size()) {
                        // Trigger click on selected row
                        JPanel selectedRow = comicRows.get(selectedIndex);
                        for (MouseListener ml : selectedRow.getMouseListeners()) {
                            ml.mouseClicked(new MouseEvent(selectedRow, MouseEvent.MOUSE_CLICKED, 
                                System.currentTimeMillis(), 0, 10, 10, 1, false, MouseEvent.BUTTON1));
                        }
                    }
                }
            }
        });
        
        dialog.setFocusable(true);
        dialog.requestFocusInWindow();
        dialog.toFront();
        dialog.setVisible(true);
        System.out.println("DEBUG: Collection Dialog made visible");
    }
    
    private void updateSelection(List<JPanel> rows, int selectedIndex, JScrollPane scrollPane) {
        for (int i = 0; i < rows.size(); i++) {
            JPanel row = rows.get(i);
            if (i == selectedIndex) {
                row.setBorder(BorderFactory.createLineBorder(ApplicationService.getAccentColor(), 2));
            } else {
                row.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));
            }
        }
        // Scroll selected row into view
        if (selectedIndex >= 0 && selectedIndex < rows.size() && scrollPane != null) {
            JPanel selectedRow = rows.get(selectedIndex);
            selectedRow.scrollRectToVisible(new Rectangle(0, 0, selectedRow.getWidth(), selectedRow.getHeight()));
        }
    }
    
    private JPanel createComicRow(String comicName, int index, Collection collection, 
                                   CollectionEntry collectionEntry, LibraryService libraryService,
                                   String lastReadComicId, JDialog dialog, List<JPanel> allRows) {
        final String[] comicIdRef = { null };
        if (collectionEntry != null && index >= 0 && index < collectionEntry.comicIds.size()) {
            comicIdRef[0] = collectionEntry.comicIds.get(index);
        }
        
        boolean isLastRead = (comicIdRef[0] != null && comicIdRef[0].equals(lastReadComicId));
        boolean isRead = (comicIdRef[0] != null && collectionEntry != null && 
                         collectionEntry.readComicIds.contains(comicIdRef[0]));
        
        String statusText = isRead ? "READ" : (isLastRead ? ">>>" : "");
        Color bgColor = isRead ? ApplicationService.getInputBackground() : ApplicationService.getBackgroundMedium();
        
        JPanel row = new JPanel(new BorderLayout());
        row.setBackground(bgColor);
        row.setBorder(BorderFactory.createEmptyBorder(3, 5, 3, 5));
        row.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        row.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        // Status label on the left
        JLabel statusLabel = new JLabel(statusText);
        statusLabel.setFont(new Font("Arial", Font.BOLD, 11));
        statusLabel.setForeground(isRead ? ApplicationService.getTextSecondary() : (isLastRead ? ApplicationService.getAccentColor() : ApplicationService.getTextPrimary()));
        statusLabel.setPreferredSize(new Dimension(50, 20));
        row.add(statusLabel, BorderLayout.WEST);
        
        JLabel nameLabel = new JLabel(comicName);
        nameLabel.setForeground(isRead ? ApplicationService.getTextSecondary() : ApplicationService.getTextPrimary());
        nameLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        row.add(nameLabel, BorderLayout.CENTER);
        
        // Mouse listener for clicking to open
        row.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    // Build ordered list of folders from collection using comic IDs (not names)
                    List<File> orderedFolders = new ArrayList<>();
                    for (String id : collectionEntry.comicIds) {
                        ComicEntry entry = libraryService.getLibraryCache().get(id);
                        if (entry != null && entry.folderPath != null) {
                            File f = new File(entry.folderPath);
                            if (f.exists()) {
                                orderedFolders.add(f);
                            }
                        }
                    }
                    
                    // Get the clicked folder using the comic ID (not name)
                    File clickedFolder = null;
                    if (comicIdRef[0] != null) {
                        ComicEntry clickedEntry = libraryService.getLibraryCache().get(comicIdRef[0]);
                        if (clickedEntry != null && clickedEntry.folderPath != null) {
                            clickedFolder = new File(clickedEntry.folderPath);
                        }
                    }
                    
                    if (clickedFolder != null && !orderedFolders.isEmpty()) {
                        dialog.dispose();
                        // Update last read comic tracking
                        String clickedComicId = libraryService.getComicId(clickedFolder);
                        if (clickedComicId != null && collectionEntry != null) {
                            libraryService.updateLastReadComic(collection.name, clickedComicId);
                        }
                        app.openCollectionViewer(clickedFolder, orderedFolders, collection.name);
                    } else {
                        JOptionPane.showMessageDialog(dialog, 
                            "Comic '" + comicName + "' not found in library.\n\nThe comic may have been renamed or moved.", 
                            "Comic Not Found", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                row.setBackground(new Color(60, 60, 60));
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
                boolean currentlyRead = (comicIdRef[0] != null && collectionEntry != null && 
                                        collectionEntry.readComicIds.contains(comicIdRef[0]));
                row.setBackground(currentlyRead ? new Color(50, 50, 50) : new Color(40, 40, 40));
            }
        });
        
        // Right-click context menu for toggling read status
        JPopupMenu contextMenu = new JPopupMenu();
        JMenuItem toggleItem = new JMenuItem(isRead ? "Mark as Unread" : "Mark as Read");
        toggleItem.addActionListener(e -> {
            if (comicIdRef[0] != null) {
                boolean nowRead = libraryService.toggleComicReadStatus(collection.name, comicIdRef[0]);
                // Update the row appearance
                String newStatus = nowRead ? "READ" : (isLastRead ? ">>>" : "");
                statusLabel.setText(newStatus);
                statusLabel.setForeground(nowRead ? ApplicationService.getTextSecondary() : (isLastRead ? ApplicationService.getAccentColor() : ApplicationService.getTextPrimary()));
                row.setBackground(nowRead ? ApplicationService.getInputBackground() : ApplicationService.getBackgroundMedium());
                nameLabel.setForeground(nowRead ? ApplicationService.getTextSecondary() : ApplicationService.getTextPrimary());
                toggleItem.setText(nowRead ? "Mark as Unread" : "Mark as Read");
            }
        });
        contextMenu.add(toggleItem);
        
        row.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    contextMenu.show(row, e.getX(), e.getY());
                }
            }
        });
        
        return row;
    }
    
    private void refreshComicList(JPanel mainPanel, Collection collection, LibraryService libraryService,
                                   CollectionEntry collectionEntry, String lastReadComicId, JDialog dialog) {
        // Refresh by reopening the dialog - simpler approach
        dialog.dispose();
        showCollectionDropdown(collection, new JPopupMenu[1]);
    }
    
    /**
     * Shows context menu for collection.
     */
    public void showCollectionContextMenu(Collection collection, JPanel source, MouseEvent e) {
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem editItem = new JMenuItem("⚙️ Edit Collection");
        editItem.addActionListener(ev -> DialogService.showEditCollectionDialog(app, collection));
        popup.add(editItem);
        
        JMenuItem deleteItem = new JMenuItem("Delete Collection");
        deleteItem.addActionListener(ev -> {
            int result = JOptionPane.showConfirmDialog(app, "Are you sure you want to delete the collection '" + collection.name + "'?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                collections.remove(collection.name);
                saveCollections();
                app.refreshDisplay();
            }
        });
        popup.add(deleteItem);
        
        popup.show(source, e.getX(), e.getY());
    }
}
